package com.quickcommerce.product.catalog.repository;

import com.quickcommerce.product.catalog.domain.Product;
import com.quickcommerce.product.catalog.dto.ProductSortOption;
import lombok.RequiredArgsConstructor;
import org.springframework.data.domain.Sort;
import org.springframework.data.r2dbc.core.R2dbcEntityTemplate;
import org.springframework.data.relational.core.query.Criteria;
import org.springframework.data.relational.core.query.Query;
import reactor.core.publisher.Flux;
import reactor.core.publisher.Mono;

/**
 * Dynamic query implementation using R2dbcEntityTemplate + Criteria API.
 * A single method handles all sort/filter combinations — no combinatorial @Query explosion.
 * All field references use Product.Fields constants (generated by @FieldNameConstants) — no magic strings.
 */
@RequiredArgsConstructor
public class ProductRepositoryCustomImpl implements ProductRepositoryCustom {

    private final R2dbcEntityTemplate template;

    @Override
    public Flux<Product> findByCategoryWithFilters(Long categoryId, ProductSortOption sortBy,
                                                    String brand, int limit, long offset) {
        Sort sort = ProductSortOption.resolve(sortBy);
        return template.select(Product.class)
                .matching(Query.query(buildCategoryCriteria(categoryId, brand))
                        .sort(sort)
                        .limit(limit)
                        .offset(offset))
                .all();
    }

    @Override
    public Mono<Long> countByCategoryWithFilters(Long categoryId, String brand) {
        return template.count(Query.query(buildCategoryCriteria(categoryId, brand)), Product.class);
    }

    private Criteria buildCategoryCriteria(Long categoryId, String brand) {
        Criteria criteria = Criteria.where(Product.Fields.categoryId).is(categoryId)
                .and(Product.Fields.isActive).is(true)
                .and(Product.Fields.isAvailable).is(true);

        if (brand != null && !brand.isBlank()) {
            criteria = criteria.and(Product.Fields.brand).is(brand);
        }
        return criteria;
    }
}
